# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Github Copilot                ║
# ╙                                                          ╜

"""Shared traceability metric calculations for CI checks and dashboards."""

from __future__ import annotations

import json
from typing import Any
from sphinx_needs.need_item import NeedItem
from sphinx_needs.data import NeedsView
from sphinx.application import Sphinx
from score_metamodel import ScoreNeedType
from pathlib import Path
from sphinx_needs.data import SphinxNeedsData
from score_metamodel.yaml_parser import load_metamodel_data

CALCULATED_METRICS = {}

def get_need_types_by_tags(needs: list[ScoreNeedType], tags: set[str]) -> list[str]:
    found_need_types: list[str] = []
    for need_type in needs:
        found_tag_set = set(need_type["tags"])
        if tags.intersection(found_tag_set):
            found_need_types.append(need_type["directive"])
    return found_need_types


def is_non_empty(value: Any) -> bool:
    """Return True if value should be treated as present for traceability checks."""
    if isinstance(value, str):
        return bool(value.strip())
    return bool(value)


def safe_percent(numerator: int, denominator: int) -> float:
    """Return percentage in range [0, 100], treating empty denominator as 100%."""
    if denominator == 0:
        return 100.0
    return (numerator / denominator) * 100.0


def calculate_requirement_metrics(
    current_requirement_needs: list[NeedItem],
) -> dict[str, Any]:
    """Calculate requirement traceability statistics for links and completeness."""
    total = len(current_requirement_needs)
    print("===============")
    reqs_with_code_link = 0
    reqs_with_test_link = 0
    reqs_fully_linked = 0
    missing_code_links_need_ids: set[str] = set()
    missing_test_links_need_ids: set[str] = set()
    missing_both_links_need_ids: set[str] = set()

    for need in current_requirement_needs:
        # Sourcecode link check
        if is_non_empty(need.get("source_code_link")):
            reqs_with_code_link += 1
        else:
            missing_code_links_need_ids.add(need.get("id"))

        # Testlink check
        if is_non_empty(need.get("testlink")):
            reqs_with_test_link += 1
        else:
            missing_test_links_need_ids.add(need.get("id"))
        # Negative check (both missing)
        if is_non_empty(need.get("testlink")) and is_non_empty(
            need.get("source_code_link")
        ):
            reqs_fully_linked += 1

    missing_both_links_need_ids = missing_code_links_need_ids.intersection(
        missing_test_links_need_ids
    )

    return {
        "total": total,
        "with_code_link": reqs_with_code_link,
        "with_test_link": reqs_with_test_link,
        "fully_linked": reqs_fully_linked,
        "with_code_link_pct": safe_percent(reqs_with_code_link, total),
        "with_test_link_pct": safe_percent(reqs_with_test_link, total),
        "fully_linked_pct": safe_percent(reqs_fully_linked, total),
        "missing_code_link_ids": sorted(missing_code_links_need_ids),
        "missing_test_link_ids": sorted(missing_test_links_need_ids),
        "not_fully_linked_ids": sorted(missing_both_links_need_ids),
    }


def calculate_test_metrics(
    test_needs: list[NeedItem], all_needs: NeedsView
) -> dict[str, Any]:
    """Calculate testcase linkage and broken testcase-reference statistics."""
    tests_total = len(test_needs)
    tests_linked = 0
    broken_references: list[dict[str, str]] = []

    for test_need in test_needs:
        # This should never happen (that it has unknown_testcase id
        # TODO: Remove this:
        test_id = str(test_need.get("id", "<unknown_testcase>"))
        partially: list[str] = test_need.get("partially_verifies")
        fully: list[str] = test_need.get("fully_verifies")
        refs = set(partially + fully)
        if refs:
            tests_linked += 1
        for ref in refs:
            if ref not in all_needs:
                broken_references.append({"testcase": test_id, "missing_need": ref})

    return {
        "total": tests_total,
        "linked_to_requirements": tests_linked,
        "linked_to_requirements_pct": safe_percent(tests_linked, tests_total),
        "broken_references": broken_references,
    }


def calculate_process_requirement_metrics(
    all_needs: NeedsView,
) -> dict[str, Any]:
    """Calculate process-requirement coverage via tool_req ``satisfies`` links."""

    process_requirements = all_needs.filter_types(["gd_req"])
    process_requirement_ids = set(process_requirements.keys())
    tool_requirements = all_needs.filter_types(["tool_req"]).filter_is_external(False)

    linked_process_requirement_ids: set[str] = set()
    for need in tool_requirements.values():
        satisfies_ids = need.get("satisfies")
        for ref_id in satisfies_ids:
            if ref_id in process_requirement_ids:
                linked_process_requirement_ids.add(ref_id)

    total = len(process_requirement_ids)
    linked_by_tool_requirements = len(linked_process_requirement_ids)
    unlinked_ids = sorted(process_requirement_ids - linked_process_requirement_ids)

    return {
        "total": total,
        "linked": linked_by_tool_requirements,
        "linked_by_tool_requirements": linked_by_tool_requirements,
        "linked_by_tool_requirements_pct": safe_percent(
            linked_by_tool_requirements, total
        ),
        "unlinked_ids": unlinked_ids,
    }


def calculate_full_need_metrics(app: Sphinx, include_external: bool):
    #            ───────────────[ Getting configuration values ]───────────────
    global CALCULATED_METRICS
    # if CALCULATED_METRICS:
    #     logger.info("Metrics calculated already, skipping re-execution")
    #     return
    all_needs: NeedsView = SphinxNeedsData(app.env).get_needs_view()

    raw_metamodel_path = app.config.score_metamodel_yaml
    override_path = Path(raw_metamodel_path) if raw_metamodel_path else None
    metamodel = load_metamodel_data(override_path)

    raw = getattr(app.config, "score_metamodel_requirement_types", "").strip()
    filter_reqs = [t.strip() for t in raw.split(",") if t.strip()]
    if not filter_reqs:
        filter_reqs = get_need_types_by_tags(
            metamodel.needs_types, {"reqiurement", "requirement_excl_process"}
        )
    #            ──────────────────[ Calculate Test Metrics ]──────────────────

    test_needs = list(all_needs.filter_types(["testcase"]).values())
    test_metrics = calculate_test_metrics(test_needs, all_needs)
    process_requirement_metrics = calculate_process_requirement_metrics(
        all_needs,
    )

    metrics_by_type: dict[str, Any] = {}
    overall_metrics: dict[str, Any] = {
        "total": 0,
        "with_code_link": 0,
        "with_test_link": 0,
        "fully_linked": 0,
    }
    for req_type in sorted(filter_reqs):
        needs_of_req_type = all_needs.filter_types([req_type]).filter_is_external(
            include_external
        )
        # We do not care if there is no requirements of this type.
        if not list(needs_of_req_type.values()):
            continue
        req_metrics = calculate_requirement_metrics(list(needs_of_req_type.values()))
        overall_metrics["total"] += req_metrics["total"]
        overall_metrics["with_code_link"] += req_metrics["with_code_link"]
        overall_metrics["with_test_link"] += req_metrics["with_test_link"]
        overall_metrics["fully_linked"] += req_metrics["fully_linked"]
        metrics_by_type[req_type] = req_metrics
    overall_metrics["with_code_link_pct"] = safe_percent(
        overall_metrics["with_code_link"], overall_metrics["total"]
    )
    overall_metrics["with_test_link_pct"] = safe_percent(
        overall_metrics["with_test_link"], overall_metrics["total"]
    )
    overall_metrics["fully_linked_pct"] = safe_percent(
        overall_metrics["fully_linked"], overall_metrics["total"]
    )

    output: dict[str, Any] = {
        "schema_version": "1",
        "generated_by": "sphinx_build",
        "overall_metrics": overall_metrics,
        "metrics_by_type": metrics_by_type,
        "tests": test_metrics,
        "process_requirements": process_requirement_metrics,
    }
    app.config.calculated_metrics = output
    CALCULATED_METRICS = output

    out_path = Path(app.outdir) / "metrics.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(output, indent=2), encoding="utf-8")
    print(f"Traceability metrics written to: {out_path}")

