# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Github Copilot                ║
# ╙                                                          ╜

"""Needpie filter functions backed by shared traceability metric calculations."""

from __future__ import annotations

import json
from pathlib import Path

from collections.abc import Sequence
from typing import Any

from sphinx_needs.need_item import NeedItem
from score_metrics.traceability_metrics import CALCULATED_METRICS

_DEFAULT_INCLUDE_EXTERNAL = False

# ╓                                                          ╖
# ║ Docstrings of functions generated by Copilot             ║
# ╙                                                          ╜


def _get_key_values(results: list[int], argument_paths: list[str]):
    """Append integer metric values selected by colon-separated paths.

    Each path is resolved against ``CALCULATED_METRICS`` (for example:
    ``"overall_metrics:total"``), converted to ``int``, and appended to
    ``results``.
    """
    metrics_json = CALCULATED_METRICS

    for raw_path in argument_paths:
        path = raw_path.strip()
        if not path:
            continue

        current: Any = metrics_json
        for key in path.split(":"):
            current = current[key]

        results.append(int(current))


def get_metrics_with_overall_total_considered(
    needs: list[Any], results: list[int], **kwargs: Any
) -> None:
    """Append selected metrics and compute remainder from overall total.

    This function appends ``overall_metrics:total`` first, then appends all
    metrics referenced by ``kwargs`` values. Finally, it replaces the first
    appended value with the remainder after subtracting all other appended
    values.
    """
    # metrics_path = str(kwargs["arg1"]) + ".json"
    # metrics_json = json.loads(Path(metrics_path).read_text(encoding="utf-8"))
    metrics_json = CALCULATED_METRICS
    results.append(int(metrics_json["overall_metrics"]["total"]))
    _get_key_values(results, [str(value) for value in kwargs.values()])
    results[0] -= sum(results[1:])
    print(results)


def get_metrics_with_custom_type_total_considered(
    needs: list[Any], results: list[int], **kwargs: Any
) -> None:
    """Append selected metrics, optionally using a custom total path.

    If the last kwarg value ends with ``":total"``, that path is used as
    baseline total and all preceding paths are treated as components; the first
    result becomes ``total - sum(components)``. Otherwise, all paths are simply
    appended as-is.
    """
    # Get the 'total' that was specified as the first value
    values = [str(value) for value in kwargs.values()]
    if values[-1].endswith(":total"):
        _get_key_values(results, [values[-1]])  # baseline total
        _get_key_values(results, values[:-1])  # components
        results[0] -= sum(results[1:])
    else:
        _get_key_values(results, values)


def get_just_metrics(needs: list[Any], results: list[int], **kwargs: Any) -> None:
    """Append selected metric values without any total/remainder calculation.

    All kwarg values are interpreted as colon-separated metric paths and
    appended to ``results`` in insertion order.
    """
    _get_key_values(results, [str(value) for value in kwargs.values()])


# def set_default_include_external(include_external: bool) -> None:
#     """Configure default behaviour for including external requirements."""
#     global _DEFAULT_INCLUDE_EXTERNAL
#     _DEFAULT_INCLUDE_EXTERNAL = bool(include_external)


# def _include_external(kwargs: dict[str, str | int | float]) -> bool:
#     """Read include_external override from filter args, else use configured default."""
#     raw = kwargs.get("arg2")
#     if raw is None:
#         return _DEFAULT_INCLUDE_EXTERNAL
#     text = str(raw).strip().lower()
#     return text in {"1", "true", "yes", "on"}
#
#
# def _requirement_types(kwargs: dict[str, str | int | float]) -> set[str]:
#     raw = str(kwargs.get("arg1", "tool_req")).strip()
#     values = {value.strip() for value in raw.split(",") if value.strip()}
#     return values or {"tool_req"}
#
#
# def pie_requirements_status(
#     needs: Sequence[NeedItem | dict[str, Any]],
#     results: list[int],
#     **kwargs: str | int | float,
# ) -> None:
#     """Dashboard status split: not implemented, implemented/incomplete, fully linked."""
#     req_types = _requirement_types(kwargs)
#     include_external = _include_external(kwargs)
#
#     all_requirements = filter_requirements(
#         needs,
#         requirement_types=req_types,
#         include_not_implemented=True,
#         include_external=include_external,
#     )
#     implemented_requirements = filter_requirements(
#         needs,
#         requirement_types=req_types,
#         include_not_implemented=False,
#         include_external=include_external,
#     )
#     summary = compute_traceability_summary(
#         all_needs=needs,
#         requirement_types=req_types,
#         include_not_implemented=False,
#         filtered_test_types=set(),
#         include_external=include_external,
#     )
#
#     not_implemented = len(all_requirements) - len(implemented_requirements)
#     fully_linked = int(summary["requirements"]["fully_linked"])
#     implemented_incomplete = len(implemented_requirements) - fully_linked
#
#     results.append(not_implemented)
#     results.append(implemented_incomplete)
#     results.append(fully_linked)
#
#
# def pie_requirements_with_code_links(
#     needs: Sequence[NeedItem | dict[str, Any]],
#     results: list[int],
#     **kwargs: str | int | float,
# ) -> None:
#     """Dashboard split: requirements with and without source code links."""
#     req_types = _requirement_types(kwargs)
#     include_external = _include_external(kwargs)
#     summary = compute_traceability_summary(
#         all_needs=needs,
#         requirement_types=req_types,
#         include_not_implemented=True,
#         filtered_test_types=set(),
#         include_external=include_external,
#     )
#
#     total = int(summary["requirements"]["total"])
#     with_code = int(summary["requirements"]["with_code_link"])
#
#     results.append(total - with_code)
#     results.append(with_code)
#
#
# def pie_requirements_with_test_links(
#     needs: Sequence[NeedItem | dict[str, Any]],
#     results: list[int],
#     **kwargs: str | int | float,
# ) -> None:
#     """Dashboard split: requirements with and without testcase links."""
#     req_types = _requirement_types(kwargs)
#     include_external = _include_external(kwargs)
#     summary = compute_traceability_summary(
#         all_needs=needs,
#         requirement_types=req_types,
#         include_not_implemented=True,
#         filtered_test_types=set(),
#         include_external=include_external,
#     )
#
#     total = int(summary["requirements"]["total"])
#     with_test = int(summary["requirements"]["with_test_link"])
#
#     results.append(total - with_test)
#     results.append(with_test)
#
#
# def pie_requirements_fully_linked(
#     needs: Sequence[NeedItem | dict[str, Any]],
#     results: list[int],
#     **kwargs: str | int | float,
# ) -> None:
#     """Dashboard split: requirements fully linked vs incomplete."""
#     req_types = _requirement_types(kwargs)
#     include_external = _include_external(kwargs)
#     summary = compute_traceability_summary(
#         all_needs=needs,
#         requirement_types=req_types,
#         include_not_implemented=True,
#         filtered_test_types=set(),
#         include_external=include_external,
#     )
#
#     total = int(summary["requirements"]["total"])
#     fully_linked = int(summary["requirements"]["fully_linked"])
#
#     results.append(total - fully_linked)
#     results.append(fully_linked)
#
#
# def pie_process_requirements_linked(
#     needs: Sequence[NeedItem | dict[str, Any]],
#     results: list[int],
#     **kwargs: str | int | float,
# ) -> None:
#     """Dashboard split: process requirements linked vs not linked."""
#     req_types = _requirement_types(kwargs)
#     include_external = _include_external(kwargs)
#     summary = compute_traceability_summary(
#         all_needs=needs,
#         requirement_types=req_types,
#         include_not_implemented=True,
#         filtered_test_types=set(),
#         include_external=include_external,
#     )
#
#     process_requirements = summary["process_requirements"]
#     total = int(process_requirements["total"])
#     linked = int(process_requirements["linked"])
#
#     results.append(total - linked)
#     results.append(linked)
