# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by CoPilot                       ║
# ╙                                                          ╜

from __future__ import annotations

import json
from pathlib import Path

import pytest
import score_metamodel.external_needs as ext_needs
from score_metamodel.external_needs import (
    ExternalNeedsSource,
    add_external_docs_sources,
    add_external_needs_json,
    get_external_needs_source,
    parse_external_needs_sources_from_DATA,
)
from sphinx.config import Config


def test_empty_list():
    assert parse_external_needs_sources_from_DATA("[]") == []


def test_external_str_does_not_start_with_at():
    assert get_external_needs_source('["noatrepo//foo/bar:baz"]') == []


def test_single_entry_with_path():
    result = parse_external_needs_sources_from_DATA('["@repo//foo/bar:baz"]')
    # IF a target has a path, it will not be reported as external needs
    assert result == []


def test_single_entry_no_path():
    result = parse_external_needs_sources_from_DATA('["@repo//:target"]')
    # If a target is not named "needs_json", it will not be reported as external needs
    assert result == []


def test_single_entry_json_no_path():
    result = parse_external_needs_sources_from_DATA('["@repo//:needs_json"]')
    assert result == [
        ExternalNeedsSource(bazel_module="repo", path_to_target="", target="needs_json")
    ]


def test_multiple_entries():
    result = parse_external_needs_sources_from_DATA(
        '["@repo1//:needs_json", "@repo2//:needs_json"]'
    )
    assert result == [
        ExternalNeedsSource(
            bazel_module="repo1", path_to_target="", target="needs_json"
        ),
        ExternalNeedsSource(
            bazel_module="repo2", path_to_target="", target="needs_json"
        ),
    ]


def test_multiple_entries_2():
    result = parse_external_needs_sources_from_DATA(
        '["@repo1//:needs_json", "@repo2//path:needs_json"]'
    )

    assert result == [
        ExternalNeedsSource(
            bazel_module="repo1", path_to_target="", target="needs_json"
        )
    ]


def test_invalid_entry():
    with pytest.raises(ValueError):
        _ = parse_external_needs_sources_from_DATA('["@not_a_valid_string"]')


def test_add_external_needs_json_appends_entry(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """add_external_needs_json should append one external needs mapping entry."""
    # Arrange
    e = ExternalNeedsSource(
        bazel_module="ext_mod", target="needs_json", path_to_target=""
    )
    config = Config()
    config.needs_external_needs = []

    runfiles_dir = tmp_path
    rel_json = Path("ext_mod+/needs_json/_build/needs/needs.json")
    json_path = runfiles_dir / rel_json
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps({"project_url": "https://example.test/repo"}), encoding="utf-8"
    )

    monkeypatch.setattr(ext_needs, "get_runfiles_dir", lambda: runfiles_dir)

    add_external_needs_json(e, config)

    assert config.needs_external_needs is not None
    assert len(config.needs_external_needs) == 1
    entry = config.needs_external_needs[0]
    assert entry["base_url"] == "https://example.test/repo/main"
    assert Path(entry["json_path"]) == json_path


def test_add_external_needs_json_missing_file_keeps_list_empty(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """add_external_needs_json should return gracefully when JSON file is missing."""
    # Arrange
    e = ExternalNeedsSource(
        bazel_module="ext_mod", target="needs_json", path_to_target=""
    )
    config = Config()
    config.needs_external_needs = []

    monkeypatch.setattr(ext_needs, "get_runfiles_dir", lambda: tmp_path)

    add_external_needs_json(e, config)

    # Assert
    assert config.needs_external_needs == []


def test_add_external_docs_sources_adds_collection(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """add_external_docs_sources should add one symlink collection entry."""
    e = ExternalNeedsSource(
        bazel_module="third_party_docs", target="docs_sources", path_to_target=""
    )
    config = Config()
    config.collections = {}

    monkeypatch.setattr(ext_needs, "get_runfiles_dir", lambda: tmp_path)

    add_external_docs_sources(e, config)

    assert config.collections is not None
    assert "third_party_docs" in config.collections
    entry = config.collections["third_party_docs"]
    assert entry["driver"] == "symlink"
    assert entry["source"] == str(tmp_path / "third_party_docs+")
    assert entry["target"] == "third_party_docs"


def test_add_external_docs_sources_ide_support_returns_without_changes(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """add_external_docs_sources should exit early for ide_support.runfiles paths."""
    e = ExternalNeedsSource(
        bazel_module="third_party_docs", target="docs_sources", path_to_target=""
    )
    config = Config()
    config.collections = {}

    monkeypatch.setattr(
        ext_needs, "get_runfiles_dir", lambda: Path("/tmp/ide_support.runfiles")
    )

    add_external_docs_sources(e, config)

    assert config.collections == {}
