# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by CoPilot                       ║
# ╙                                                          ╜

from __future__ import annotations

import json
from pathlib import Path

import pytest
import score_metamodel.external_needs as ext_needs
from score_metamodel.external_needs import (
    ExternalNeedsSource,
    _add_needs_json_file,  # pyright: ignore[reportPrivateUsage] - white-box unit test
    add_external_docs_sources,
    add_external_needs_json,
    get_external_needs_source,
    parse_external_needs_sources_from_DATA,
)
from sphinx.config import Config


def test_empty_list():
    assert parse_external_needs_sources_from_DATA("[]") == []


def test_external_str_is_neither_at_nor_slash():
    # Labels that start with neither "@" nor "//" are not bazel needs sources.
    assert get_external_needs_source('["noatrepo/foo/bar:baz"]') == []


def test_same_repo_entry_with_path():
    # A same-repo `//pkg:needs_json` mount now parses as a local source that
    # carries its sub-package path.
    result = parse_external_needs_sources_from_DATA('["//foo/bar:needs_json"]')
    assert result == [
        ExternalNeedsSource(
            bazel_module="",
            path_to_target="foo/bar",
            target="needs_json",
            is_local=True,
        )
    ]


def test_same_repo_root_entry():
    result = parse_external_needs_sources_from_DATA('["//:needs_json"]')
    assert result == [
        ExternalNeedsSource(
            bazel_module="",
            path_to_target="",
            target="needs_json",
            is_local=True,
        )
    ]


def test_cross_module_sub_package_entry():
    # A cross-module sub-package target now parses (previously rejected) and
    # keeps its path so the runfiles path can be built correctly.
    result = parse_external_needs_sources_from_DATA('["@repo//foo/bar:needs_json"]')
    assert result == [
        ExternalNeedsSource(
            bazel_module="repo",
            path_to_target="foo/bar",
            target="needs_json",
            is_local=False,
        )
    ]


def test_single_entry_with_path_non_target():
    # A target that is not needs_json / docs_sources is not reported as an external needs source.
    result = parse_external_needs_sources_from_DATA('["@repo//foo/bar:baz"]')
    assert result == []


def test_single_entry_no_path():
    result = parse_external_needs_sources_from_DATA('["@repo//:target"]')
    # If a target is not named "needs_json", it will not be reported as external needs
    assert result == []


def test_single_entry_json_no_path():
    result = parse_external_needs_sources_from_DATA('["@repo//:needs_json"]')
    assert result == [
        ExternalNeedsSource(bazel_module="repo", path_to_target="", target="needs_json")
    ]


def test_multiple_entries():
    result = parse_external_needs_sources_from_DATA(
        '["@repo1//:needs_json", "@repo2//:needs_json"]'
    )
    assert result == [
        ExternalNeedsSource(
            bazel_module="repo1", path_to_target="", target="needs_json"
        ),
        ExternalNeedsSource(
            bazel_module="repo2", path_to_target="", target="needs_json"
        ),
    ]


def test_multiple_entries_2():
    # Both targets are named "needs_json" but one is a sub-package target, so the path is preserved.
    result = parse_external_needs_sources_from_DATA(
        '["@repo1//:needs_json", "@repo2//path:needs_json"]'
    )

    assert result == [
        ExternalNeedsSource(
            bazel_module="repo1", path_to_target="", target="needs_json"
        ),
        ExternalNeedsSource(
            bazel_module="repo2",
            path_to_target="path",
            target="needs_json",
            is_local=False,
        ),
    ]


def test_invalid_entry():
    with pytest.raises(ValueError):
        _ = parse_external_needs_sources_from_DATA('["@not_a_valid_string"]')


def test_add_external_needs_json_appends_entry(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """add_external_needs_json should append one external needs mapping entry."""
    # Arrange
    e = ExternalNeedsSource(
        bazel_module="ext_mod", target="needs_json", path_to_target=""
    )
    config = Config()
    config.needs_external_needs = []

    runfiles_dir = tmp_path
    rel_json = Path("ext_mod+/needs_json/_build/needs/needs.json")
    json_path = runfiles_dir / rel_json
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps({"project_url": "https://example.test/repo"}), encoding="utf-8"
    )

    monkeypatch.setattr(ext_needs, "get_runfiles_dir", lambda: runfiles_dir)

    add_external_needs_json(e, config)

    assert config.needs_external_needs is not None
    assert len(config.needs_external_needs) == 1
    entry = config.needs_external_needs[0]
    assert entry["base_url"] == "https://example.test/repo/main"
    assert Path(entry["json_path"]) == json_path


def test_add_external_needs_json_appends_entry_local(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A same-repo mount resolves under `_main/<path>/<target>/…`."""
    e = ExternalNeedsSource(
        bazel_module="",
        target="needs_json",
        path_to_target="src/tests/e2e/external_needs/producer",
        is_local=True,
    )
    config = Config()
    config.needs_external_needs = []

    runfiles_dir = tmp_path
    rel_json = Path(
        "_main/src/tests/e2e/external_needs/producer/needs_json/_build/needs/needs.json"
    )
    json_path = runfiles_dir / rel_json
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps({"project_url": "https://example.test/local"}), encoding="utf-8"
    )

    monkeypatch.setattr(ext_needs, "get_runfiles_dir", lambda: runfiles_dir)

    add_external_needs_json(e, config)

    assert config.needs_external_needs is not None
    assert len(config.needs_external_needs) == 1
    entry = config.needs_external_needs[0]
    assert entry["base_url"] == "https://example.test/local/main"
    assert Path(entry["json_path"]) == json_path


def test_add_needs_json_file_appends_entry(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """_add_needs_json_file should load from a :needs_json_file target."""
    # Arrange: create the needs.json at the runfiles path
    rel_json = Path("ext_mod+/needs.json")
    json_path = tmp_path / rel_json
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps({"project_url": "https://example.test/json-file"}), encoding="utf-8"
    )

    runfiles_dir = tmp_path
    config = Config()
    config.needs_external_needs = []

    monkeypatch.setattr(ext_needs, "get_runfiles_dir", lambda: runfiles_dir)

    # Act
    e = ExternalNeedsSource(
        bazel_module="ext_mod",
        target="needs_json_file",
        path_to_target="",
        is_local=False,
    )
    _add_needs_json_file(e, config)

    # Assert
    assert config.needs_external_needs is not None
    assert len(config.needs_external_needs) == 1
    entry = config.needs_external_needs[0]
    assert entry["base_url"] == "https://example.test/json-file/main"
    assert Path(entry["json_path"]) == json_path


def test_add_external_needs_json_missing_file_keeps_list_empty(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """add_external_needs_json should return gracefully when JSON file is missing."""
    # Arrange
    e = ExternalNeedsSource(
        bazel_module="ext_mod", target="needs_json", path_to_target=""
    )
    config = Config()
    config.needs_external_needs = []

    monkeypatch.setattr(ext_needs, "get_runfiles_dir", lambda: tmp_path)

    add_external_needs_json(e, config)

    # Assert
    assert config.needs_external_needs == []


def test_add_external_docs_sources_adds_collection(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """add_external_docs_sources should add one symlink collection entry."""
    e = ExternalNeedsSource(
        bazel_module="third_party_docs", target="docs_sources", path_to_target=""
    )
    config = Config()
    config.collections = {}

    monkeypatch.setattr(ext_needs, "get_runfiles_dir", lambda: tmp_path)

    add_external_docs_sources(e, config)

    assert config.collections is not None
    assert "third_party_docs" in config.collections
    entry = config.collections["third_party_docs"]
    assert entry["driver"] == "symlink"
    assert entry["source"] == str(tmp_path / "third_party_docs+")
    assert entry["target"] == "third_party_docs"


def test_add_external_docs_sources_local_sub_package(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A same-repo sub-package `docs_sources` mount resolves under `_main/<path>`.

    Mirrors test_add_external_needs_json_appends_entry_local but for the
    `docs_sources` path: the local branch stages under `_main/…`, appends
    `path_to_target`, and the collection key falls through the
    `bazel_module + path_to_target` join (bazel_module empty for a local mount).
    """
    e = ExternalNeedsSource(
        bazel_module="",
        target="docs_sources",
        path_to_target="src/tests/e2e/external_needs/producer",
        is_local=True,
    )
    config = Config()
    config.collections = {}

    monkeypatch.setattr(ext_needs, "get_runfiles_dir", lambda: tmp_path)

    add_external_docs_sources(e, config)

    assert config.collections is not None
    key = "src/tests/e2e/external_needs/producer"
    assert key in config.collections
    entry = config.collections[key]
    assert entry["driver"] == "symlink"
    assert entry["source"] == str(
        tmp_path / "_main" / "src/tests/e2e/external_needs/producer"
    )
    assert entry["target"] == key


def test_add_external_docs_sources_local_root_key_fallback(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A same-repo root `docs_sources` mount falls back to the `_main` key.

    With both bazel_module and path_to_target empty, the key join yields "" and
    the `or "_main"` fallback names the collection, while the source stays at the
    `_main` runfiles root.
    """
    e = ExternalNeedsSource(
        bazel_module="",
        target="docs_sources",
        path_to_target="",
        is_local=True,
    )
    config = Config()
    config.collections = {}

    monkeypatch.setattr(ext_needs, "get_runfiles_dir", lambda: tmp_path)

    add_external_docs_sources(e, config)

    assert config.collections is not None
    assert "_main" in config.collections
    entry = config.collections["_main"]
    assert entry["driver"] == "symlink"
    assert entry["source"] == str(tmp_path / "_main")
    assert entry["target"] == "_main"


def test_add_external_docs_sources_ide_support_returns_without_changes(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """add_external_docs_sources should exit early for ide_support.runfiles paths."""
    e = ExternalNeedsSource(
        bazel_module="third_party_docs", target="docs_sources", path_to_target=""
    )
    config = Config()
    config.collections = {}

    monkeypatch.setattr(
        ext_needs, "get_runfiles_dir", lambda: Path("/tmp/ide_support.runfiles")
    )

    add_external_docs_sources(e, config)

    assert config.collections == {}
