# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# As problems are rare, we group each ecosystem into "all-in-one" PRs.

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: chore(github-actions)

  - package-ecosystem: pip
    directory: /src
    schedule:
      interval: weekly
    groups:
      python:
        patterns:
          - "*"
    commit-message:
      prefix: chore(pip)

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly
    groups:
      pre-commit:
        patterns:
          - "*"
    commit-message:
      prefix: chore(pre-commit)

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: weekly
    groups:
      docker:
        patterns:
          - "*"
    commit-message:
      prefix: chore(docker)
