# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Github Copilot                ║
# ╙                                                          ╜

"""Traceability gate: read a metrics JSON and enforce coverage thresholds.

This script is the CI gate for a metrics.json based workflow:
    docs build  →  score_metamodel extension writes metrics.json
    CI gate     →  traceability_gate --metrics-json metrics.json [--min-* ...]

The gate never parses needs.json itself; it only reads the pre-computed
schema-v1 metrics file produced by the docs build.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

_SUPPORTED_SCHEMA_VERSION = "1"


def _print_type_summary(need_type: str, metrics: dict[str, Any]) -> None:
    req = metrics["requirements"]
    tst = metrics["tests"]
    req_total = req["total"]
    req_with_code_link = req["with_code_link"]
    req_with_code_link_pct = req["with_code_link_pct"]
    req_with_test_link = req["with_test_link"]
    req_with_test_link_pct = req["with_test_link_pct"]
    req_fully_linked = req["fully_linked"]
    req_fully_linked_pct = req["fully_linked_pct"]
    tst_total = tst["total"]
    tst_linked_to_requirements = tst["linked_to_requirements"]
    tst_linked_to_requirements_pct = tst["linked_to_requirements_pct"]
    tst_broken_references = tst["broken_references"]

    print(f"[{need_type}]")
    print(
        f"  Requirements with source links: "
        f"{req_with_code_link}/{req_total} ({req_with_code_link_pct:.2f}%)"
    )
    print(
        f"  Requirements with test links:   "
        f"{req_with_test_link}/{req_total} ({req_with_test_link_pct:.2f}%)"
    )
    print(
        f"  Requirements fully linked:      "
        f"{req_fully_linked}/{req_total} ({req_fully_linked_pct:.2f}%)"
    )
    print(
        f"  Tests linked to requirements:   "
        f"{tst_linked_to_requirements}/{tst_total} "
        f"({tst_linked_to_requirements_pct:.2f}%)"
    )
    print(f"  Broken test references:         {len(tst_broken_references)}")
    if tst_broken_references:
        for item in tst_broken_references:
            print(f"    - {item['testcase']} -> {item['missing_need']}")


def _check_type_thresholds(
    need_type: str,
    metrics: dict[str, Any],
    min_req_code: float,
    min_req_test: float,
    min_req_fully_linked: float,
    min_tests_linked: float,
    fail_on_broken_test_refs: bool,
) -> list[str]:
    failures: list[str] = []
    req = metrics["requirements"]
    tst = metrics["tests"]
    req_with_code_link_pct = req["with_code_link_pct"]
    req_with_test_link_pct = req["with_test_link_pct"]
    req_fully_linked_pct = req["fully_linked_pct"]
    tst_linked_to_requirements_pct = tst["linked_to_requirements_pct"]
    tst_broken_references = tst["broken_references"]
    prefix = f"[{need_type}] "

    if req_with_code_link_pct < min_req_code:
        failures.append(
            f"{prefix}requirements with code links "
            f"{req_with_code_link_pct:.2f}% < {min_req_code:.2f}%"
        )
    if req_with_test_link_pct < min_req_test:
        failures.append(
            f"{prefix}requirements with test links "
            f"{req_with_test_link_pct:.2f}% < {min_req_test:.2f}%"
        )
    if req_fully_linked_pct < min_req_fully_linked:
        failures.append(
            f"{prefix}requirements fully linked "
            f"{req_fully_linked_pct:.2f}% < {min_req_fully_linked:.2f}%"
        )
    if tst_linked_to_requirements_pct < min_tests_linked:
        failures.append(
            f"{prefix}tests linked to requirements "
            f"{tst_linked_to_requirements_pct:.2f}% < {min_tests_linked:.2f}%"
        )
    if fail_on_broken_test_refs and tst_broken_references:
        failures.append(
            f"{prefix}broken testcase references found: {len(tst_broken_references)}"
        )
    return failures


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Read a traceability metrics JSON (schema v1) and enforce coverage "
            "thresholds. Exits 0 on pass, 2 on threshold failure, 1 on input error."
        )
    )
    parser.add_argument(
        "--metrics-json",
        required=True,
        help="Path to the metrics JSON produced by the docs build.",
    )
    parser.add_argument(
        "--need-type",
        default=None,
        help=(
            "Check only this need type (e.g. 'tool_req'). "
            "If omitted, all types present in the JSON are checked."
        ),
    )
    parser.add_argument(
        "--min-req-code",
        type=float,
        default=0.0,
        help="Minimum %% of requirements that must have a source_code_link.",
    )
    parser.add_argument(
        "--min-req-test",
        type=float,
        default=0.0,
        help="Minimum %% of requirements that must have a testlink.",
    )
    parser.add_argument(
        "--min-req-fully-linked",
        type=float,
        default=0.0,
        help="Minimum %% of requirements that must have both source_code_link and testlink.",
    )
    parser.add_argument(
        "--min-tests-linked",
        type=float,
        default=0.0,
        help="Minimum %% of testcases that must reference at least one requirement.",
    )
    parser.add_argument(
        "--require-all-links",
        action="store_true",
        help="Shortcut: sets all --min-* to 100 and enables --fail-on-broken-test-refs.",
    )
    parser.add_argument(
        "--fail-on-broken-test-refs",
        action="store_true",
        help="Fail when any testcase references an unknown requirement ID.",
    )

    args = parser.parse_args()

    if args.require_all_links:
        args.min_req_code = 100.0
        args.min_req_test = 100.0
        args.min_req_fully_linked = 100.0
        args.min_tests_linked = 100.0
        args.fail_on_broken_test_refs = True

    metrics_path = Path(args.metrics_json)
    workspace_dir = os.environ.get("BUILD_WORKSPACE_DIRECTORY", "").strip()
    if not metrics_path.is_absolute() and workspace_dir:
        metrics_path = Path(workspace_dir) / metrics_path
    if not metrics_path.exists():
        print(f"Error: metrics JSON not found: {metrics_path}", file=sys.stderr)
        return 1

    data: dict[str, Any] = json.loads(metrics_path.read_text(encoding="utf-8"))

    schema_version = data.get("schema_version")
    if schema_version != _SUPPORTED_SCHEMA_VERSION:
        print(
            f"Error: unsupported schema_version {schema_version!r} "
            f"(expected {_SUPPORTED_SCHEMA_VERSION!r})",
            file=sys.stderr,
        )
        return 1

    metrics_by_type: dict[str, Any] = data["metrics_by_type"]
    types_to_check = (
        [args.need_type] if args.need_type else list(metrics_by_type.keys())
    )

    print(f"Traceability gate input: {metrics_path}")
    print("-" * 72)

    failures: list[str] = []
    for need_type in types_to_check:
        if need_type not in metrics_by_type:
            available = list(metrics_by_type.keys())
            failures.append(
                f"need type '{need_type}' not found in metrics JSON "
                f"(available: {available})"
            )
            continue
        _print_type_summary(need_type, metrics_by_type[need_type])
        failures.extend(
            _check_type_thresholds(
                need_type,
                metrics_by_type[need_type],
                args.min_req_code,
                args.min_req_test,
                args.min_req_fully_linked,
                args.min_tests_linked,
                args.fail_on_broken_test_refs,
            )
        )

    print("-" * 72)
    if failures:
        print("Threshold check failed:")
        for msg in failures:
            print(f"  - {msg}")
        return 2

    print("Threshold check passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
