# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Github Copilot                ║
# ╙                                                          ╜

"""
Tests for the traceability gate script using metrics schema v2,
including overall statistics coverage.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

import scripts_bazel.traceability_gate as gate


def _derive_overall_metrics(metrics_by_type: dict[str, Any]) -> dict[str, Any]:
    """
    Derive overall requirement metrics from all need types.

    Args:
        metrics_by_type: Per-type requirement metrics map.

    Returns:
        Aggregated requirement totals and percentages.
    """
    total = 0
    with_code_link = 0
    with_test_link = 0
    fully_linked = 0

    for item in metrics_by_type.values():
        total += int(item["total"])
        with_code_link += int(item["with_code_link"])
        with_test_link += int(item["with_test_link"])
        fully_linked += int(item["fully_linked"])

    if total == 0:
        with_code_link_pct = 0.0
        with_test_link_pct = 0.0
        fully_linked_pct = 0.0
    else:
        with_code_link_pct = (with_code_link / total) * 100.0
        with_test_link_pct = (with_test_link / total) * 100.0
        fully_linked_pct = (fully_linked / total) * 100.0

    return {
        "total": total,
        "with_code_link": with_code_link,
        "with_test_link": with_test_link,
        "fully_linked": fully_linked,
        "with_code_link_pct": with_code_link_pct,
        "with_test_link_pct": with_test_link_pct,
        "fully_linked_pct": fully_linked_pct,
    }


def _write_metrics_json(
    tmp_path: Path,
    metrics_by_type: dict[str, Any] | None = None,
    tests: dict[str, Any] | None = None,
    schema_version: str = "2",
) -> Path:
    """
    Write a metrics.json file in schema v2 format.

    Args:
        tmp_path: Temporary directory for test artifacts.
        metrics_by_type: Optional per-type requirement metrics.
        tests: Optional global test linkage metrics.
        schema_version: Schema version string.

    Returns:
        Path to the written JSON file.
    """
    if metrics_by_type is None:
        metrics_by_type = {
            "tool_req": {
                "include_not_implemented": False,
                "include_external": False,
                "total": 4,
                "with_code_link": 3,
                "with_test_link": 2,
                "fully_linked": 2,
                "with_code_link_pct": 75.0,
                "with_test_link_pct": 50.0,
                "fully_linked_pct": 50.0,
            }
        }

    if tests is None:
        tests = {
            "total": 3,
            "linked_to_requirements": 2,
            "linked_to_requirements_pct": 66.67,
            "broken_references": [],
        }

    payload: dict[str, Any] = {
        "schema_version": schema_version,
        "generated_by": "sphinx_build",
        "overall_metrics": _derive_overall_metrics(metrics_by_type),
        "metrics_by_type": metrics_by_type,
        "tests": tests,
    }

    out = tmp_path / "metrics.json"
    out.write_text(json.dumps(payload), encoding="utf-8")
    return out


def _run_main(
    monkeypatch: pytest.MonkeyPatch,
    args: list[str],
) -> int:
    """
    Run ``gate.main()`` with patched ``sys.argv``.

    Args:
        monkeypatch: Pytest monkeypatch fixture.
        args: CLI arguments excluding program name.

    Returns:
        Exit code returned by ``gate.main()``.
    """
    monkeypatch.setattr("sys.argv", ["traceability_gate.py", *args])
    return gate.main()


def test_gate_passes_when_thresholds_met(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    metrics_json = _write_metrics_json(tmp_path)

    rc = _run_main(
        monkeypatch,
        [
            "--metrics-json",
            str(metrics_json),
            "--min-req-code",
            "70",
            "--min-req-test",
            "50",
            "--min-tests-linked",
            "60",
        ],
    )
    captured = capsys.readouterr()

    assert rc == 0
    assert "Threshold check passed." in captured.out


def test_gate_fails_when_threshold_not_met(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    metrics_json = _write_metrics_json(tmp_path)

    rc = _run_main(
        monkeypatch,
        ["--metrics-json", str(metrics_json), "--min-req-code", "100"],
    )
    captured = capsys.readouterr()

    assert rc == 2
    assert "Threshold check failed:" in captured.out
    assert "[tool_req] requirements with code links" in captured.out


def test_gate_require_all_links_fails(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    metrics_json = _write_metrics_json(tmp_path)

    rc = _run_main(
        monkeypatch,
        ["--metrics-json", str(metrics_json), "--require-all-links"],
    )
    captured = capsys.readouterr()

    assert rc == 2
    assert "Threshold check failed:" in captured.out


def test_gate_fail_on_broken_test_refs(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    metrics_by_type = {
        "tool_req": {
            "include_not_implemented": False,
            "include_external": False,
            "total": 1,
            "with_code_link": 1,
            "with_test_link": 1,
            "fully_linked": 1,
            "with_code_link_pct": 100.0,
            "with_test_link_pct": 100.0,
            "fully_linked_pct": 100.0,
        }
    }
    tests = {
        "total": 2,
        "linked_to_requirements": 2,
        "linked_to_requirements_pct": 100.0,
        "broken_references": [{"testcase": "TC_X", "missing_need": "REQ_UNKNOWN"}],
    }
    metrics_json = _write_metrics_json(
        tmp_path, metrics_by_type=metrics_by_type, tests=tests
    )

    rc = _run_main(
        monkeypatch,
        ["--metrics-json", str(metrics_json), "--fail-on-broken-test-refs"],
    )
    captured = capsys.readouterr()

    assert rc == 2
    assert "broken testcase references found: 1" in captured.out


def test_gate_specific_need_type_only(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    metrics_by_type = {
        "tool_req": {
            "include_not_implemented": False,
            "include_external": False,
            "total": 2,
            "with_code_link": 2,
            "with_test_link": 2,
            "fully_linked": 2,
            "with_code_link_pct": 100.0,
            "with_test_link_pct": 100.0,
            "fully_linked_pct": 100.0,
        },
        "comp_req": {
            "include_not_implemented": False,
            "include_external": False,
            "total": 5,
            "with_code_link": 0,
            "with_test_link": 0,
            "fully_linked": 0,
            "with_code_link_pct": 0.0,
            "with_test_link_pct": 0.0,
            "fully_linked_pct": 0.0,
        },
    }
    tests = {
        "total": 1,
        "linked_to_requirements": 1,
        "linked_to_requirements_pct": 100.0,
        "broken_references": [],
    }
    metrics_json = _write_metrics_json(
        tmp_path, metrics_by_type=metrics_by_type, tests=tests
    )

    rc = _run_main(
        monkeypatch,
        [
            "--metrics-json",
            str(metrics_json),
            "--need-type",
            "tool_req",
            "--require-all-links",
        ],
    )
    captured = capsys.readouterr()

    assert rc == 0
    assert "[tool_req]" in captured.out
    assert "[comp_req]" not in captured.out


def test_gate_unknown_need_type_fails(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    metrics_json = _write_metrics_json(tmp_path)

    rc = _run_main(
        monkeypatch,
        ["--metrics-json", str(metrics_json), "--need-type", "nonexistent_req"],
    )
    captured = capsys.readouterr()

    assert rc == 2
    assert "not found in metrics JSON" in captured.out


def test_gate_unsupported_schema_version(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    metrics_json = _write_metrics_json(tmp_path, schema_version="99")

    rc = _run_main(monkeypatch, ["--metrics-json", str(metrics_json)])
    captured = capsys.readouterr()

    assert rc == 1
    assert "unsupported schema_version" in captured.err


def test_gate_missing_file_returns_error(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    missing = tmp_path / "does_not_exist.json"

    rc = _run_main(monkeypatch, ["--metrics-json", str(missing)])
    captured = capsys.readouterr()

    assert rc == 1
    assert "metrics JSON not found" in captured.err


def test_gate_missing_metrics_by_type_returns_error(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    payload = {
        "schema_version": "2",
        "generated_by": "sphinx_build",
        "overall_metrics": {
            "total": 0,
            "with_code_link": 0,
            "with_test_link": 0,
            "fully_linked": 0,
            "with_code_link_pct": 0.0,
            "with_test_link_pct": 0.0,
            "fully_linked_pct": 0.0,
        },
        "tests": {
            "total": 0,
            "linked_to_requirements": 0,
            "linked_to_requirements_pct": 0.0,
            "broken_references": [],
        },
    }
    metrics_json = tmp_path / "metrics.json"
    metrics_json.write_text(json.dumps(payload), encoding="utf-8")

    rc = _run_main(monkeypatch, ["--metrics-json", str(metrics_json)])
    captured = capsys.readouterr()

    assert rc == 1
    assert "missing or empty 'metrics_by_type'" in captured.err


def test_gate_missing_tests_section_returns_error(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    metrics_by_type = {
        "tool_req": {
            "include_not_implemented": False,
            "include_external": False,
            "total": 1,
            "with_code_link": 1,
            "with_test_link": 1,
            "fully_linked": 1,
            "with_code_link_pct": 100.0,
            "with_test_link_pct": 100.0,
            "fully_linked_pct": 100.0,
        }
    }
    payload = {
        "schema_version": "2",
        "generated_by": "sphinx_build",
        "overall_metrics": _derive_overall_metrics(metrics_by_type),
        "metrics_by_type": metrics_by_type,
    }
    metrics_json = tmp_path / "metrics.json"
    metrics_json.write_text(json.dumps(payload), encoding="utf-8")

    rc = _run_main(monkeypatch, ["--metrics-json", str(metrics_json)])
    captured = capsys.readouterr()

    assert rc == 1
    assert "missing 'tests' section" in captured.err
