# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Github Copilot                ║
# ╙                                                          ╜

"""Tests for traceability_gate.py."""

import json
import subprocess
import sys
from pathlib import Path

_MY_PATH = Path(__file__).parent

_GATE_SCRIPT = _MY_PATH.parent / "traceability_gate.py"


def _write_metrics_json(tmp_path: Path, metrics_by_type: dict | None = None) -> Path:
    """Write a schema-v1 metrics JSON and return its path."""
    if metrics_by_type is None:
        metrics_by_type = {
            "tool_req": {
                "include_not_implemented": False,
                "include_external": False,
                "requirements": {
                    "total": 4,
                    "with_code_link": 3,
                    "with_test_link": 2,
                    "fully_linked": 2,
                    "with_code_link_pct": 75.0,
                    "with_test_link_pct": 50.0,
                    "fully_linked_pct": 50.0,
                    "missing_code_link_ids": ["REQ_4"],
                    "missing_test_link_ids": ["REQ_3", "REQ_4"],
                    "not_fully_linked_ids": ["REQ_3", "REQ_4"],
                },
                "tests": {
                    "total": 3,
                    "filtered_test_types": [],
                    "linked_to_requirements": 2,
                    "linked_to_requirements_pct": 66.67,
                    "broken_references": [],
                },
            }
        }
    payload = {
        "schema_version": "1",
        "generated_by": "sphinx_build",
        "metrics_by_type": metrics_by_type,
    }
    out = tmp_path / "metrics.json"
    out.write_text(json.dumps(payload), encoding="utf-8")
    return out


def _run_gate(metrics_json: Path, extra_args: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, _GATE_SCRIPT, "--metrics-json", str(metrics_json)]
        + extra_args,
        capture_output=True,
        text=True,
    )


def test_gate_passes_when_thresholds_met(tmp_path: Path) -> None:
    metrics_json = _write_metrics_json(tmp_path)

    result = _run_gate(
        metrics_json,
        ["--min-req-code", "70", "--min-req-test", "50", "--min-tests-linked", "60"],
    )

    assert result.returncode == 0
    assert "Threshold check passed." in result.stdout


def test_gate_fails_when_threshold_not_met(tmp_path: Path) -> None:
    metrics_json = _write_metrics_json(tmp_path)

    result = _run_gate(
        metrics_json,
        ["--min-req-code", "100"],
    )

    assert result.returncode == 2
    assert "Threshold check failed:" in result.stdout
    assert "[tool_req] requirements with code links" in result.stdout


def test_gate_require_all_links_fails(tmp_path: Path) -> None:
    metrics_json = _write_metrics_json(tmp_path)

    result = _run_gate(metrics_json, ["--require-all-links"])

    assert result.returncode == 2
    assert "Threshold check failed:" in result.stdout


def test_gate_fail_on_broken_refs(tmp_path: Path) -> None:
    metrics_by_type = {
        "tool_req": {
            "include_not_implemented": False,
            "include_external": False,
            "requirements": {
                "total": 1,
                "with_code_link": 1,
                "with_test_link": 1,
                "fully_linked": 1,
                "with_code_link_pct": 100.0,
                "with_test_link_pct": 100.0,
                "fully_linked_pct": 100.0,
                "missing_code_link_ids": [],
                "missing_test_link_ids": [],
                "not_fully_linked_ids": [],
            },
            "tests": {
                "total": 2,
                "filtered_test_types": [],
                "linked_to_requirements": 2,
                "linked_to_requirements_pct": 100.0,
                "broken_references": [
                    {"testcase": "TC_X", "missing_need": "REQ_UNKNOWN"}
                ],
            },
        }
    }
    metrics_json = _write_metrics_json(tmp_path, metrics_by_type)

    result = _run_gate(metrics_json, ["--fail-on-broken-test-refs"])

    assert result.returncode == 2
    assert "broken testcase references found:" in result.stdout


def test_gate_specific_need_type(tmp_path: Path) -> None:
    metrics_by_type = {
        "tool_req": {
            "include_not_implemented": False,
            "include_external": False,
            "requirements": {
                "total": 2,
                "with_code_link": 2,
                "with_test_link": 2,
                "fully_linked": 2,
                "with_code_link_pct": 100.0,
                "with_test_link_pct": 100.0,
                "fully_linked_pct": 100.0,
                "missing_code_link_ids": [],
                "missing_test_link_ids": [],
                "not_fully_linked_ids": [],
            },
            "tests": {
                "total": 1,
                "filtered_test_types": [],
                "linked_to_requirements": 1,
                "linked_to_requirements_pct": 100.0,
                "broken_references": [],
            },
        },
        "comp_req": {
            "include_not_implemented": False,
            "include_external": False,
            "requirements": {
                "total": 5,
                "with_code_link": 0,
                "with_test_link": 0,
                "fully_linked": 0,
                "with_code_link_pct": 0.0,
                "with_test_link_pct": 0.0,
                "fully_linked_pct": 0.0,
                "missing_code_link_ids": ["C1", "C2", "C3", "C4", "C5"],
                "missing_test_link_ids": ["C1", "C2", "C3", "C4", "C5"],
                "not_fully_linked_ids": ["C1", "C2", "C3", "C4", "C5"],
            },
            "tests": {
                "total": 0,
                "filtered_test_types": [],
                "linked_to_requirements": 0,
                "linked_to_requirements_pct": 100.0,
                "broken_references": [],
            },
        },
    }
    metrics_json = _write_metrics_json(tmp_path, metrics_by_type)

    # Gate only on tool_req (which is fully linked) — comp_req failures are ignored
    result = _run_gate(
        metrics_json,
        ["--need-type", "tool_req", "--require-all-links"],
    )

    assert result.returncode == 0
    assert "[tool_req]" in result.stdout
    assert "[comp_req]" not in result.stdout


def test_gate_unknown_need_type_fails(tmp_path: Path) -> None:
    metrics_json = _write_metrics_json(tmp_path)

    result = _run_gate(metrics_json, ["--need-type", "nonexistent_req"])

    assert result.returncode == 2
    assert "not found in metrics JSON" in result.stdout


def test_gate_unsupported_schema_version(tmp_path: Path) -> None:
    bad = tmp_path / "bad.json"
    bad.write_text(
        json.dumps({"schema_version": "99", "metrics_by_type": {}}), encoding="utf-8"
    )

    result = _run_gate(bad, [])

    assert result.returncode == 1
    assert "unsupported schema_version" in result.stderr


def test_gate_missing_file_returns_error(tmp_path: Path) -> None:
    result = _run_gate(tmp_path / "does_not_exist.json", [])

    assert result.returncode == 1
    assert "not found" in result.stderr
