# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

"""Generates a live_preview script in the workspace root.

Usage: bazel run //:gen_live_preview
The generated ./live_preview script uses ibazel to keep :docs_src_dir fresh
and sphinx-autobuild to serve with browser auto-reload.
"""

import os
import stat
import textwrap
from pathlib import Path

if __name__ == "__main__":
    workspace = os.environ.get("BUILD_WORKSPACE_DIRECTORY", "")
    if not workspace:
        raise SystemExit("Must be run via 'bazel run', not directly.")

    source_dir = os.environ["SOURCE_DIRECTORY"]

    script = textwrap.dedent(f"""\
        #!/usr/bin/env python3
        # Generated by: bazel run //:gen_live_preview
        # Re-run that command to regenerate after changing docs() parameters.

        import os
        import subprocess
        import sys
        import threading
        from pathlib import Path

        WORKSPACE = Path({repr(workspace)})
        SOURCE_DIR = {repr(source_dir)}
        SRC_TREE = WORKSPACE / "bazel-bin" / "docs_src_dir" / SOURCE_DIR
        BUILD_DIR = WORKSPACE / "_build"
        VENV = WORKSPACE / ".venv_docs"
        PORT = int(os.environ.get("PORT", "8000"))


        def _ibazel_loop() -> None:
            \"\"\"Runs ibazel to keep :docs_src_dir up-to-date.\"\"\"
            subprocess.run(
                ["ibazel", "build", ":docs_src_dir"],
                cwd=WORKSPACE,
            )


        if __name__ == "__main__":
            sphinx_autobuild = VENV / "bin" / "sphinx-autobuild"
            python = VENV / "bin" / "python"
            if not python.exists():
                sys.exit(
                    "Missing .venv_docs — run: bazel run //:ide_support"
                )

            # Initial build of the source tree
            print("Building source tree (initial)...", flush=True)
            subprocess.run(
                ["bazel", "build", ":docs_src_dir"], cwd=WORKSPACE, check=True
            )

            # Start ibazel in background to keep source tree fresh
            threading.Thread(target=_ibazel_loop, daemon=True).start()

            # sphinx-autobuild watches the materialized tree and handles reload
            print(f"Serving at http://localhost:{{PORT}}")
            print("Edit docs sources — the page will reload automatically.")
            print("Ctrl-C to stop.")
            cmd = [str(sphinx_autobuild)] if sphinx_autobuild.exists() else [
                str(python), "-m", "sphinx_autobuild",
            ]
            subprocess.run(
                cmd + [
                    str(SRC_TREE),
                    str(BUILD_DIR),
                    "--jobs", "auto",
                    "--define=skip_rescanning_via_source_code_linker=1",
                    f"--define=needscfg_outpath={{WORKSPACE / SOURCE_DIR / 'ubproject.toml'}}",
                    f"--port={{PORT}}",
                ],
                cwd=WORKSPACE,
            )
    """)

    output = Path(workspace) / "live_preview"
    output.write_text(script)
    output.chmod(output.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"Generated {output}")
    print("Run it with:  ./live_preview")
