# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

"""Generates a live_preview script in the workspace root.

Usage: bazel run //:gen_live_preview
The generated ./live_preview script runs `bazel run //:docs` in a watch loop
and serves _build/ via HTTP.
"""

import os
import stat
import textwrap
from pathlib import Path

if __name__ == "__main__":
    workspace = os.environ.get("BUILD_WORKSPACE_DIRECTORY", "")
    if not workspace:
        raise SystemExit("Must be run via 'bazel run', not directly.")

    source_dir = os.environ["SOURCE_DIRECTORY"]

    script = textwrap.dedent(f"""\
        #!/usr/bin/env python3
        # Generated by: bazel run //:gen_live_preview
        # Re-run that command to regenerate after changing docs() parameters.

        import http.server
        import os
        import subprocess
        import threading
        import time
        from pathlib import Path

        WORKSPACE = Path({repr(workspace)})
        SOURCE_DIR = WORKSPACE / {repr(source_dir)}
        BUILD_DIR = WORKSPACE / "_build"
        PORT = int(os.environ.get("PORT", "8000"))

        _rebuild_event = threading.Event()


        def _mtimes(directory: Path) -> dict:
            result = {{}}
            for p in directory.rglob("*"):
                if p.is_file():
                    try:
                        result[str(p)] = p.stat().st_mtime
                    except OSError:
                        pass
            return result


        def _watch_loop(watched_dirs: list) -> None:
            previous = {{}}
            for d in watched_dirs:
                previous.update(_mtimes(Path(d)))
            while True:
                time.sleep(1)
                current = {{}}
                for d in watched_dirs:
                    current.update(_mtimes(Path(d)))
                if current != previous:
                    previous = current
                    _rebuild_event.set()


        def _build_loop() -> None:
            while True:
                _rebuild_event.wait()
                _rebuild_event.clear()
                print("\\nSources changed — rebuilding...", flush=True)
                subprocess.run(["bazel", "run", "//:docs"], cwd=WORKSPACE)
                print("Done. Refresh http://localhost:{{PORT}}", flush=True)


        class _ReloadingHandler(http.server.SimpleHTTPRequestHandler):
            \"\"\"Injects a polling auto-reload snippet into HTML responses.\"\"\"

            _SNIPPET = (
                "<script>"
                "setInterval(()=>{{fetch(location.href,{{cache:'no-store'}}).then(r=>r.text())"
                ".then(t=>{{if(t!==document._last){{document._last=t;location.reload()}}}})}},2000);"
                "document._last=document.documentElement.outerHTML;"
                "</script>"
            )

            def __init__(self, *args, **kwargs):
                super().__init__(*args, directory=str(BUILD_DIR), **kwargs)

            def end_headers(self):
                self.send_header("Cache-Control", "no-store")
                super().end_headers()

            def copyfile(self, source, outputfile):
                if self.path.endswith(".html") or self.path == "/":
                    content = source.read()
                    modified = content.replace(
                        b"</body>", self._SNIPPET.encode() + b"</body>", 1
                    )
                    outputfile.write(modified)
                else:
                    super().copyfile(source, outputfile)

            def log_message(self, fmt, *args):
                pass  # silence per-request logs


        if __name__ == "__main__":
            print(f"Building docs (initial)...", flush=True)
            subprocess.run(["bazel", "run", "//:docs"], cwd=WORKSPACE, check=True)

            threading.Thread(
                target=_watch_loop, args=([str(SOURCE_DIR)],), daemon=True
            ).start()
            threading.Thread(target=_build_loop, daemon=True).start()

            print(f"Serving at http://localhost:{{PORT}}")
            print("Edit docs sources — the page will reload automatically.")
            print("Ctrl-C to stop.")
            with http.server.ThreadingHTTPServer(("", PORT), _ReloadingHandler) as httpd:
                httpd.serve_forever()
    """)

    output = Path(workspace) / "live_preview"
    output.write_text(script)
    output.chmod(output.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"Generated {output}")
    print("Run it with:  ./live_preview")
