# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Run Bazel Tests
on:
  workflow_call:
jobs:
  _tests:
    runs-on: ubuntu-latest
    steps:
      - name: 🛡️ Harden Runner
        if: github.repository_owner == 'eclipse-score'
        uses: step-security/harden-runner@v2.21.0
        with:
          egress-policy: audit

      - name: Install Graphviz
        uses: eclipse-score/apt-install@main
        with:
          packages: graphviz
          cache: false

      - name: Checkout repository (Handle all events)
        uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref || github.event.pull_request.head.ref || github.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: Setup Bazel with shared caching
        uses: eclipse-score/cicd-actions/setup-bazel-cache@cache
        with:
          disk-cache-key: ${{ github.job }}

      - name: Setup venv
        run: bazel run --lockfile_mode=error //:ide_support

      - name: Prepare test report directory
        run: mkdir -p tests-report

      - name: Run public docs.bzl integration tests
        run: .venv_docs/bin/python -m pytest -vv src/tests/docs_bzl --junitxml=tests-report/docs_bzl.xml

      - name: Run bazel test targets
        run: bazel test --lockfile_mode=error //... --build_tests_only

      - name: Build all targets
        # Skip tests, since some are non buildable negative tests
        run: bazel build --lockfile_mode=error //... -- -//src/tests/...

      - name: Prepare bundled test report
        if: ${{ !cancelled() }}
        # Follow Symlinks via '-L' to copy correctly
        run: rsync -amL --include='*/' --include='test.xml' --include='test.log' --exclude='*' bazel-testlogs/ tests-report/

      - name: Upload bundled test report
        # No need to upload something that doesn't exist.
        # This would be skipped anyway if the step before isn't running
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tests-report
          path: tests-report
