# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: PR Checks

on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:

      - name: 🛡️ Harden Runner
        if: github.repository_owner == 'eclipse-score'
        uses: step-security/harden-runner@v2.18.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          disk-cache: true
          repository-cache: true
          bazelisk-cache: true

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit checks
        run: pre-commit run -a

  pinact:
    name: Run pinact
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v6

      - name: Install pinact
        run: go install github.com/suzuki-shunsuke/pinact/v4/cmd/pinact@v4.1.0

      - name: Run pinact
        id: pinact
        continue-on-error: true
        run: |
          "$(go env GOPATH)/bin/pinact" run --format sarif > sarif.json

      - name: Upload SARIF
        if: ${{ !cancelled() && hashFiles('sarif.json') != '' }}
        uses: github/codeql-action/upload-sarif@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4.31.9
        with:
          sarif_file: sarif.json
          category: pinact
