# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("//:docs.bzl", "docs")

docs(
    source_dir = "docs",
    project = "Basic Test",
    project_url = "https://github.com/eclipse-score/docs-as-code",
    data = ["supporting-example.txt"],
    test_sources = ["src/tests/docs_bzl/scenarios/basic_docs"],
)
